// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void search() {
    // Test name: Search
    // Step # | name | target | value
    // 1 | open | /index.php | 
    driver.get("http://automationpractice.com/index.php");
    // 2 | setWindowSize | 1034x668 | 
    driver.manage().window().setSize(new Dimension(1034, 668));
    // 3 | click | id=search_query_top | 
    driver.findElement(By.id("search_query_top")).click();
    // 4 | type | id=search_query_top | summer
    driver.findElement(By.id("search_query_top")).sendKeys("summer");
    // 5 | click | name=submit_search | 
    driver.findElement(By.name("submit_search")).click();
    // 6 | assertText | css=.heading-counter | 4 results have been found.
    // numbers result
    assertThat(driver.findElement(By.cssSelector(".heading-counter")).getText(), is("4 results have been found."));
  }
}
